version: 2
updates:
  - package-ecosystem: 'terraform'
    pull-request-branch-name:
      separator: "-"
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    pull-request-branch-name:
      separator: "-"  
    directory: '/'
    schedule:
      interval: 'daily'