name: "[Example Workflow]"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write
  actions: read
  checks: read
  deployments: none
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  statuses: none


jobs:
  # generate a branch name  
  branch_name:
    name: "Generate a safe branch name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@main
  
  # generate workspace name
  workspace_name:
    name: "Generate the workspace name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-workspace.yml@main
  
  # generate smevar tag
  semvar_tag:
    needs: [branch_name]
    name: "Generate the semvar tag value"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-semvar-tag.yml@main
    with:
      branch_name: ${{ needs.branch_name.outputs.parsed }}"
    secrets: inherit

  # artificial step to output vars for easier debugging
  variable_generation_completed:
    runs-on: "ubuntu-latest"
    needs: [branch_name, workspace_name, semvar_tag]
    name: "Generated standard variables"
    steps:
      - name: "Output generated variables"
        run: |
          echo "== BRANCH =="
          echo "Raw: ${{ needs.branch_name.outputs.raw }}"
          echo "Parsed: ${{ needs.branch_name.outputs.parsed }}"
          echo "Alphanumeric: ${{ needs.branch_name.outputs.alphanumeric }}"
          echo "== WORKSPACE =="
          echo "Name: ${{ needs.workspace_name.outputs.name }}"
          echo "== SEMVAR =="
          echo "Tag: ${{ needs.semvar_tag.outputs.tag }}"

  # LINTING
  # run linting for terraform
  tf_lint:
    name: "Run terraform linting"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/linting-infrastructure-terraform.yml@v1.6.0
    with:
      directory: "./terraform"
      terraform_version: "1.6.4"
      terraform_wrapper: false

  # tfsec for terraform 
  tfsec_analysis:
    name: "Run TFSec against the code base"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-to-github-security.yml@v1.6.0
          
  # example terraform build stage
  terraform_account_build:
    name: "Terraform Account Plan and Apply"
    needs: [workspace_name, semvar_tag]
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform.yml@v1.6.0
    with:
      terraform_version: "1.6.4"
      terraform_directory: "./terraform/account"
      terraform_apply: true
      # this would be replaced with the dynamic value from needs.workspace_name.output.name
      # but we're just using sandbox account and single env, so use default
      terraform_workspace: "default" 
      # normally would need some logic to decide this based on branch name etc
      # - if its true we would then need to pass workspace_manager_aws_account_id & 
      #   workspace_manager_aws_iam_role as well
      is_ephemeral: false
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      PAGERDUTY_TOKEN: "NONE"
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [branch_name, workspace_name, semvar_tag, variable_generation_completed, terraform_account_build]
    steps:
      - name: "Output data"
        run: |
          echo "== BRANCH =="
          echo "Raw: ${{ needs.branch_name.outputs.raw }}"
          echo "Parsed: ${{ needs.branch_name.outputs.parsed }}"
          echo "Alphanumeric: ${{ needs.branch_name.outputs.alphanumeric }}"
          echo "== WORKSPACE =="
          echo "Name: ${{ needs.workspace_name.outputs.name }}"
          echo "== SEMVAR =="
          echo "Tag: ${{ needs.semvar_tag.outputs.tag }}"
          



