name: "[Scheduled] Terraform Destroy"

on:
  workflow_dispatch:
  schedule:
    # 6pm every day except Sundays
    - cron: '0 18 * * 0-6'

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Get terraform version"
        uses: ministryofjustice/opg-github-actions/.github/actions/terraform-version@v2.7.3
        id: tf_version
        with:
          terraform_directory: "./terraform/account/"

      - uses: hashicorp/setup-terraform@8fa54e78fa196965551aa8c4a4eae3aee5568620 # pin@v2.0.0
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}

      - name: configure AWS credentials for terraform
        uses: aws-actions/configure-aws-credentials@2119c3b07593cce0acbcee3240f1787eebcf4697 # pin@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
          aws-region: eu-west-1
          role-duration-seconds: 1800
          role-session-name: SandboxTerraformGithubAction
      
      - name: terraform init
        working-directory: ./terraform/account
        run: terraform init --input=false --lock-timeout=5m

      - name: terraform destroy
        working-directory: ./terraform/account
        run: terraform destroy --auto-approve

