name: "[Workflow] Plan & Apply"

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  security-events: write
  actions: read
  checks: read
  deployments: none
  issues: none
  packages: none
  pull-requests: read
  repository-projects: none
  statuses: none


jobs:
  # generate a branch name  
  branch_name:
    name: "Generate a safe branch name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-branch-name.yml@v1.32.0
  
  # generate workspace name
  workspace_name:
    name: "Generate the workspace name"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-workspace.yml@v1.32.0
  
  # LINTING
  # run linting for terraform
  tf_lint:
    name: "Run terraform linting"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/linting-infrastructure-terraform.yml@v1.32.0
    with:
      directory: "./terraform"
      terraform_version: "1.6.4"
      terraform_wrapper: false

  # tfsec for terraform 
  tfsec_analysis:
    name: "Run TFSec against the code base"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/analysis-infrastructure-tfsec-to-github-security.yml@v1.32.0
  
  # generate semver tag
  semver_tag:
    needs: [branch_name, tfsec_analysis, tf_lint]
    name: "Generate the semver tag value"
    uses: ministryofjustice/opg-github-workflows/.github/workflows/data-parse-semver-tag.yml@v1.32.0
    with:
      branch_name: ${{ needs.branch_name.outputs.parsed }}
    secrets: inherit

  # artificial step to output vars for easier debugging
  variable_generation_completed:
    runs-on: "ubuntu-latest"
    needs: [branch_name, workspace_name, semver_tag]
    name: "Generated standard variables"
    steps:
      - name: "Output generated variables"
        run: |
          echo "== BRANCH =="
          echo "Raw: ${{ needs.branch_name.outputs.raw }}"
          echo "Parsed: ${{ needs.branch_name.outputs.parsed }}"
          echo "Alphanumeric: ${{ needs.branch_name.outputs.alphanumeric }}"
          echo "== WORKSPACE =="
          echo "Name: ${{ needs.workspace_name.outputs.name }}"
          echo "== semver =="
          echo "Tag: ${{ needs.semver_tag.outputs.tag }}"

  # terraform apply stage
  terraform_account:
    name: "Terraform Account [Apply: ${{ github.ref == 'refs/heads/main'}}]"
    needs: [variable_generation_completed, tf_lint, workspace_name, semver_tag]
    uses: ministryofjustice/opg-github-workflows/.github/workflows/build-infrastructure-terraform.yml@v1.33.0
    with:
      terraform_version: "1.6.4"
      terraform_directory: "./terraform/account"
      terraform_apply: ${{ github.ref == 'refs/heads/main' && true || false }}
      terraform_workspace: "default" 
      is_ephemeral: false
    secrets:
      AWS_ACCESS_KEY_ID_ACTIONS: ${{ secrets.AWS_ACCESS_KEY_ID_ACTIONS }}
      AWS_SECRET_ACCESS_KEY_ACTIONS: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACTIONS }}
      PAGERDUTY_TOKEN: "NONE"
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
  
  end:
    name: 'End of workflow'
    runs-on: 'ubuntu-latest'
    needs: [terraform_account]
    steps:
      - name: "Output data"
        run: |
          echo "== BRANCH =="
          echo "Raw: ${{ needs.branch_name.outputs.raw }}"
          echo "Parsed: ${{ needs.branch_name.outputs.parsed }}"
          echo "Alphanumeric: ${{ needs.branch_name.outputs.alphanumeric }}"
          echo "== WORKSPACE =="
          echo "Name: ${{ needs.workspace_name.outputs.name }}"
          echo "== semver =="
          echo "Tag: ${{ needs.semver_tag.outputs.tag }}"
          



